services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: spapi
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app -d spapi"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    env_file:
      - .env
    environment:
      PG_DSN: postgresql://app:app@db:5432/spapi
    depends_on:
      db:
        condition: service_healthy
    command: ["python","main.py","--posted-after","2025-08-01T00:00:00Z"]
volumes:
  pgdata:
